spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/zupbank?createDatabaseIfNotExist=true&serverTimezone=UTC
  hikari:
    maximum-pool-size: 5
    minimum-idle: 3
    hikari.idle-time: 10000
  jpa.show-sql: true
